version: '3.7'
services:
  ar:
    image: vubui/apollo-react-template
    ports:
      - ${HTTP_PORT:-80}:4000
    volumes:
      - ar-logs:/logs
    environment:
      - ROOT_URL
      - CDN_URL
      - GRAPHQL_ENDPOINT
      - REST_ENDPOINT
      - MONGO_URL
      - QUERY_LIMIT
      - LOG_FILE=/logs/ar.log
      - TZ
    healthcheck:
      test: ['CMD', 'wget', '--spider', 'http://localhost:4000']
volumes:
  ar-logs:
