version: '3.7'
services:
  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - ${MONGO_EXPRESS_PORT:-8081}:8081
    healthcheck:
      test: ['CMD', 'wget', '--spider', 'http://localhost:8081']
